### ISSUE TITLE
Some new client-specific (signature-) strings I've become aware of...

### ISSUE THREAD

**Issue by mstroeck** [hellogustav/elixir_email_reply_parser#10]
... since this is Outlook, probably worth to add.

EN: Get Outlook for Android
EN: Get Outlook for iOS

DE: Outlook für iOS  beziehen
DE: Outlook für Android beziehen

**Comment by slavo2** [comment]
Hi @mstroeck please could you add some email with full context?
(i.e. containing email it is being replied to and a reply with one of those strings)

**Comment by mstroeck** [comment]
OK!

**Comment by slavo2** [comment]
Done.

Commits:
https://github.com/hellogustav/elixir_email_reply_parser/commit/bc1a3920b3280d20b3d0917f9b157d1a06a934b2
https://github.com/hellogustav/elixir_email_reply_parser/commit/ae704daed7f593997d339f60713fb4d53ee5ecdc

Closing.
